# Generated by Django 5.0.6 on 2024-07-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelexpense',
            name='batch_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expensereport',
            name='pdf_file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
