# Generated by Django 5.0.6 on 2024-07-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_employeejoining'),
    ]

    operations = [
        migrations.CreateModel(
            name='userCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comId', models.CharField(max_length=50)),
                ('comName', models.CharField(max_length=50)),
                ('comGST', models.CharField(max_length=50)),
                ('comCIN', models.CharField(max_length=50)),
                ('comCont', models.IntegerField()),
                ('comEmail', models.CharField(max_length=50)),
                ('comDLNum1', models.CharField(max_length=50)),
                ('comDLNum2', models.CharField(max_length=50)),
                ('comPanNum', models.CharField(max_length=50)),
                ('comAdd', models.CharField(max_length=50)),
                ('comCity', models.TextField(max_length=50)),
                ('comState', models.TextField(max_length=50)),
                ('comPin', models.IntegerField(max_length=50)),
            ],
        ),
    ]
