# Generated by Django 5.0.6 on 2024-07-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_travelexpense_batch_id_alter_expensereport_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelexpense',
            name='batch_id',
            field=models.IntegerField(blank=True),
        ),
    ]
