# Generated by Django 5.0.6 on 2024-07-03 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_alter_travelexpense_batch_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelexpense',
            name='batch_id',
        ),
    ]
