# Generated by Django 5.0.6 on 2024-07-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_remove_travelexpense_batch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelexpense',
            name='batch_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
