# Generated by Django 5.0.6 on 2024-07-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0005_travelexpense_batch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='travelexpense',
            name='accommodation',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='travelexpense',
            name='food_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='travelexpense',
            name='miscellaneous',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='travelexpense',
            name='other',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='travelexpense',
            name='total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='travelexpense',
            name='transport_fare',
            field=models.IntegerField(),
        ),
    ]
